# Generated by Django 5.0.1 on 2024-02-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_orderitem_price_orderitem_qty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItems',
        ),
    ]
