# Generated by Django 5.0.1 on 2024-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_product_usd_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='usd_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
