# Generated by Django 5.0.1 on 2024-03-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wish list'},
        ),
    ]
