# Generated by Django 5.0.1 on 2024-03-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_order_total_use_amount_vendor_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='seller_imgs/'),
        ),
    ]
