# Generated by Django 5.0.1 on 2024-03-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_order_total_amout'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='usd_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
