# Generated by Django 5.0.1 on 2024-03-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_orderitems_usd_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_use_amount',
            new_name='total_usd_amount',
        ),
    ]
