# Generated by Django 5.0.1 on 2024-04-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_total_use_amount_order_total_usd_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatorgory',
            name='cat_img',
            field=models.ImageField(null=True, upload_to='category_imgs/'),
        ),
    ]
