# Generated by Django 4.2.7 on 2024-06-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_productcatorgory_cat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcatorgory',
            name='detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcatorgory',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
