# Generated by Django 4.2.7 on 2024-06-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_product_details_alter_productcatorgory_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatorgory',
            name='detail',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
